meta_product_name: "Triez Avec Ben"
meta_title: "Triez Avec Ben - Le Tri Facile"
meta_description: "Le tri, c'est la vie."
meta_image: "cover-picture1200x630.png" # should exist in `app/assets/images/
